services:
  redis-dev:
    image: redis:latest
    container_name: redis-dev
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  spring-boot-dev:
    build:
      context: .
      dockerfile: backend-spring/Dockerfile
    container_name: spring-boot-dev
    ports:
      - "8081:8080"
    depends_on:
      - redis-dev
    environment:
      - SPRING_PROFILES_ACTIVE=docker-dev
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

  python-ai-dev:
    build:
      context: .
      dockerfile: backend-ai/Dockerfile
    container_name: python-ai-dev
    ports:
      - "8001:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

  frontend-dev:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - NGINX_CONFIG=nginx-dev.conf
    container_name: frontend-dev
    ports:
      - "3001:80"
    depends_on:
      spring-boot-dev:
        condition: service_started
      python-ai-dev:
        condition: service_started

volumes:
  redis-data:
